// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SkillsProWebApiService.Models
{
    public partial class EmployeeSkillsMapping
    {
        [Key]
        public string MapId { get; set; }

        [Required]
        public string EmployeeId { get; set; }

        [Required]
        public string SkillId { get; set; }
    }

    public partial class ExtendedEmployeeSkillsMapping
    {
        [Key]
        public string MapId { get; set; }

        [Required]
        public string EmployeeId { get; set; }

        [Required]
        public string EmployeeName { get; set; }

        [Required]
        public string SkillId { get; set; }

        [Required]
        public string SkillName { get; set; }
    }
}